### ISSUE TITLE
Monocypher 4.0.2 is out

### ISSUE THREAD

**Issue by LoupVaillant** [tillitis/tkey-libs#17]
Hi,

Monocypher 4.0.2 is out, with 2 notable changes:

- Dotentially substantial performance improvements for Poly1305 (depends on the compiler, the latest ones may not benefit).
- Argon2 bug fix (incorrect results when used with multiple lanes). _(Though who would ever use Argon2 on the Tkey?)_

I believe updating is not urgent, we just need to avoid multi-lane Argon2 on the Tkey for now. Sorry about the bug. Of course apps that don't use Argon2 (that would be all of them?) are safe. They, and associated CDI, can be preserved.

**Comment by dehanj** [comment]
Thanks for the update, we really appreciate that you take the time and write an issue for us.

You are right. No apps are affected by this as of now, but we will add it to our todo.
